[package]
name = "clarity-ab-tester"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clarity = { path = "../stacks-blockchain/clarity" }
stacks-common = { path = "../stacks-blockchain/stacks-common" }
blockstack-core = { path = "../stacks-blockchain" }
diesel = { version = "2.1.3", features = ["sqlite"] }
env_logger = "0.10.0"
log = "0.4.20"
toml = "0.8.2"
serde = "1.0.188"
serde_derive = "1.0.188"
anyhow = "1.0.75"
thiserror = "1.0.49"
rand = "0.8.5"
clap = { version = "4.4.6", features = ["default", "derive"] }
hex = "0.4.3"
crossterm = "0.27.0"
ratatui = "0.23.0"
