[app]
db_path = "./appdb.sqlite"

[baseline]
# ;; Configure chainstate for the baseline
chainstate_path = "/home/cylwit/stacks/mainnet/"
#chainstate_path = "/tmp/chainstate1/"
chain_id = 1

[[environment]]
name = "interpreter"
# ;; Uncomment to provide a custom chainstate path for this environment.
# ;; If not provided, a randomly generated temporary directory will be used.
# chainstate_path = ""

# ;; Specify the Clarity runtime to be used in this environment.
runtime = "Interpreter"

[[environment]]
name = "wasm"
runtime = "Wasm"