name: Property Testings

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  property-testing:
    name: Property Testing
    runs-on: ubuntu-latest
    env:
      PROPTEST_CASES: 100
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4

      - name: Use Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Run
        run: cargo test --test wasm-generation --test standard

  notification:
    name: Notification
    runs-on: ubuntu-latest
    needs: property-testing
    if: ${{ failure() }}
    steps:
    - name: Notify on Failure
      uses: maxkomarychev/oction-create-issue@v0.7.1
      with:
        token: ${{ secrets.GH_TOKEN }}
        title: "[Test] Property testing coverage has failed"
